# Generated by Django 5.2.6 on 2025-09-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_profile_formacion_cocinerodeldia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocinerodeldia',
            options={'ordering': ['-fecha', '-id']},
        ),
        migrations.AddField(
            model_name='cocinerodeldia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
