# Generated by Django 5.2.6 on 2025-10-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
