# Generated by Django 5.2.6 on 2025-10-13 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('subscription', '0002_usersubscription_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionBurger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='promotions/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
                ('promotion_burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='promotion.promotionburger')),
            ],
            options={
                'unique_together': {('promotion_burger', 'ingredient')},
            },
        ),
        migrations.CreateModel(
            name='PromotionSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotion.promotionburger')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptionplan')),
            ],
            options={
                'unique_together': {('promotion', 'subscription')},
            },
        ),
    ]
