# Generated by Django 5.2.6 on 2025-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
        migrations.AddField(
            model_name='publication',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
