# Generated by Django 5.2.6 on 2025-11-12 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerBurger', '0001_initial'),
        ('post', '0002_remove_publication_image_publication_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='custom_burger_id',
        ),
        migrations.AddField(
            model_name='publication',
            name='custom_burger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='customerBurger.customburger'),
        ),
    ]
