# Generated by Django 5.2.6 on 2025-11-15 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerBurger', '0001_initial'),
        ('post', '0004_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_burger__isnull', False)), fields=('user', 'custom_burger'), name='uniq_user_custom_burger_publication'),
        ),
    ]
