# Generated by Django 5.2.6 on 2025-10-29 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_ingredient_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBurger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='custom_burgers/')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_burgers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomBurgerUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='customerBurger.customburger')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burgers_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relación Burger - Usuario',
                'verbose_name_plural': 'Relaciones Burger - Usuario',
                'constraints': [models.UniqueConstraint(fields=('custom_burger', 'usuario'), name='uniq_custom_burger_usuario')],
            },
        ),
        migrations.CreateModel(
            name='CustomIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='customerBurger.customburger')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
            ],
            options={
                'unique_together': {('custom_burger', 'ingredient')},
            },
        ),
    ]
