# Generated by Django 5.2.6 on 2025-10-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_subscriptionplan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_monthly_publications',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
