# Generated by Django 5.2.6 on 2025-10-10 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_subscriptionplan_max_monthly_publications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
