# Generated by Django 5.2.6 on 2025-11-04 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('customerBurger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_burger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerBurger.customburger'),
        ),
    ]
