# Generated by Django 5.2.6 on 2025-11-23 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_custom_burger'),
        ('menuburger', '0002_menuburger_is_gluten_free_menuburger_is_vegan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='menu_burger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menuburger.menuburger'),
        ),
    ]
