# Generated by Django 5.2.6 on 2025-10-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
