# Generated by Django 5.2.6 on 2025-11-04 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerBurger', '0001_initial'),
        ('order', '0004_order_expiration_time'),
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_burger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customerBurger.customburger'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotion.promotionburger'),
        ),
    ]
