# Generated by Django 5.2.6 on 2025-11-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuburger', '0002_menuburger_is_gluten_free_menuburger_is_vegan'),
        ('order', '0006_order_pickup_date_order_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='menu_burger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menuburger.menuburger'),
        ),
    ]
