# Generated by Django 5.2.6 on 2025-11-22 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_ingredient_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBurger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(blank=True, null=True, upload_to='menu_burgers/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuBurgerIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
                ('menu_burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menuburger.menuburger')),
            ],
            options={
                'unique_together': {('menu_burger', 'ingredient')},
            },
        ),
    ]
