# Generated by Django 5.2.6 on 2025-11-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuburger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuburger',
            name='is_gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuburger',
            name='is_vegan',
            field=models.BooleanField(default=False),
        ),
    ]
